-- ==========================================
-- DIMENSIÓN MARCA
-- ==========================================

CREATE TABLE dim_marca (
    id_marca INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca VARCHAR(50) NOT NULL UNIQUE
);


-- ==========================================
-- DIMENSIÓN MODELO
-- ==========================================

CREATE TABLE dim_modelo (
    id_modelo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_marca INTEGER NOT NULL,
    modelo VARCHAR(150) NOT NULL,

    CONSTRAINT fk_modelo_marca
        FOREIGN KEY (id_marca)
        REFERENCES dim_marca(id_marca),

    CONSTRAINT uq_modelo_marca
        UNIQUE (id_marca, modelo)
);


-- ==========================================
-- DIMENSIÓN FECHA
-- ==========================================

CREATE TABLE dim_fecha (
    id_periodo INTEGER PRIMARY KEY,
    fecha DATE NOT NULL UNIQUE,
    año INTEGER NOT NULL,
    mes_numero INTEGER NOT NULL,
    mes_nombre VARCHAR(20) NOT NULL,
    trimestre INTEGER NOT NULL,
    semestre INTEGER NOT NULL,
    año_mes VARCHAR(7) NOT NULL UNIQUE
);

INSERT INTO dim_fecha (
    id_periodo,
    fecha,
    año,
    mes_numero,
    mes_nombre,
    trimestre,
    semestre,
    año_mes
)
SELECT
    TO_CHAR(fecha, 'YYYYMM')::INTEGER AS id_periodo,
    fecha,
    EXTRACT(YEAR FROM fecha)::INTEGER AS año,
    EXTRACT(MONTH FROM fecha)::INTEGER AS mes_numero,

    CASE EXTRACT(MONTH FROM fecha)::INTEGER
        WHEN 1 THEN 'Enero'
        WHEN 2 THEN 'Febrero'
        WHEN 3 THEN 'Marzo'
        WHEN 4 THEN 'Abril'
        WHEN 5 THEN 'Mayo'
        WHEN 6 THEN 'Junio'
        WHEN 7 THEN 'Julio'
        WHEN 8 THEN 'Agosto'
        WHEN 9 THEN 'Septiembre'
        WHEN 10 THEN 'Octubre'
        WHEN 11 THEN 'Noviembre'
        WHEN 12 THEN 'Diciembre'
    END AS mes_nombre,

    EXTRACT(QUARTER FROM fecha)::INTEGER AS trimestre,

    CASE
        WHEN EXTRACT(MONTH FROM fecha) <= 6 THEN 1
        ELSE 2
    END AS semestre,

    TO_CHAR(fecha, 'YYYY-MM') AS año_mes

FROM GENERATE_SERIES(
    '2020-01-01'::DATE,
    '2030-12-01'::DATE,
    '1 month'::INTERVAL
) AS fecha;